# Generated by Django 5.1.4 on 2025-02-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinformations',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
