# Generated by Django 5.1.4 on 2025-02-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userPost',
        ),
    ]
