# Generated by Django 5.1.4 on 2025-02-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_userpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='userPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theUser', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
